name: remote ssh command
on:
  push:
    branches:
      - main # Change this to your main branch name


jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.PUBLIC_IP }}
        username: root
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd /var/www/html/DICOM-Website
          git pull origin main
          npm install
          npm run build
