name: remote ssh command
on:
  push:
    branches:
      - main # Change this to your main branch name


jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: root
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd /root/DICOM-frontend/DICOM-Website
          git pull origin main
          docker-compose down
          docker-compose up --build -d
          docker system prune
